<?php

/**
 * @file
 * Hooks and customizations for the organization module.
 */

declare(strict_types=1);

use Drupal\Core\Render\Element;

/**
 * Prepares variables for organization templates.
 *
 * Default template: organization.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the organization information
 *     and any fields attached to the organization. Properties used:
 *     - #organization: A \Drupal\organization\Entity\Organization object. The
 *       organization entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_organization(array &$variables) {
  $variables['organization'] = $variables['elements']['#organization'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
