<?php

/**
 * @file
 * Contains farm_plant_type.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_plant_type\Hook\FarmPlantTypeHooks;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_form_display_alter().
 */
#[LegacyHook]
function farm_plant_type_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  \Drupal::service(FarmPlantTypeHooks::class)->entityFormDisplayAlter($form_display, $context);
}

/**
 * Implements hook_entity_view_display_alter().
 */
#[LegacyHook]
function farm_plant_type_entity_view_display_alter(EntityViewDisplayInterface $display, array $context) {
  \Drupal::service(FarmPlantTypeHooks::class)->entityViewDisplayAlter($display, $context);
}
