<?php

/**
 * @file
 * Contains farm_birth.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function farm_birth_asset_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // Only alter animal assets.
  if ($entity->bundle() != 'animal') {
    return;
  }

  // Add a link to the asset's birth log.
  if (!empty($build['birthdate'][0])) {
    /** @var \Drupal\Core\Entity\EntityStorageInterface $log_storage */
    $log_storage = \Drupal::service('entity_type.manager')->getStorage('log');
    $log_ids = $log_storage->getQuery()
      ->accessCheck(TRUE)
      ->condition('type', 'birth')
      ->condition('asset', $entity->id())
      ->execute();

    // Render a link to the log with a title of the timestamp field value.
    if (!empty($log_ids)) {
      $title = $build['birthdate'][0];
      $build['birthdate'][0] = [
        '#type' => 'link',
        '#title' => $title,
        '#url' => Url::fromRoute('entity.log.canonical', ['log' => reset($log_ids)]),
      ];
    }
  }
}
