<?php

/**
 * @file
 * Contains farm_owner.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_owner\Hook\FarmOwnerHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_owner_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(FarmOwnerHooks::class)->entityBaseFieldInfo($entity_type);
}
