<?php

/**
 * @file
 * Hooks and customizations for the plan module.
 */

declare(strict_types=1);

use Drupal\Core\Render\Element;

/**
 * Prepares variables for plan templates.
 *
 * Default template: plan.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the plan information and any
 *     fields attached to the plan. Properties used:
 *     - #plan: A \Drupal\plan\Entity\Plan object. The plan entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_plan(array &$variables) {
  $variables['plan'] = $variables['elements']['#plan'] ?? NULL;
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
