<?php

/**
 * @file
 * The farmOS Export CSV module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_export_csv\Hook\FarmExportCsvHooks;
use Drupal\farm_export_csv\Form\EntityCsvActionForm;
use Drupal\farm_export_csv\Routing\EntityCsvActionRouteProvider;

/**
 * Implements hook_entity_type_build().
 */
#[LegacyHook]
function farm_export_csv_entity_type_build(array &$entity_types) {

  \Drupal::service(FarmExportCsvHooks::class)->entityTypeBuild($entity_types);
}
