<?php

/**
 * @file
 * Contains farm_ui_views_test.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_ui_views_test\Hook\FarmUiViewsTestHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_ui_views_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(FarmUiViewsTestHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_farm_ui_views_base_fields().
 */
#[LegacyHook]
function farm_ui_views_test_farm_ui_views_base_fields(string $entity_type) {
  return \Drupal::service(FarmUiViewsTestHooks::class)->farmUiViewsBaseFields($entity_type);
}
