<?php

/**
 * @file
 * Contains farm_comment_plan.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_comment_plan\Hook\FarmCommentPlanHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_comment_plan_entity_base_field_info(EntityTypeInterface $entity_type)
{
    return \Drupal::service(FarmCommentPlanHooks::class)->entityBaseFieldInfo($entity_type);
}
