services:
  _defaults:
    autowire: true
  asset.inventory:
    class: Drupal\farm_inventory\AssetInventory
  Drupal\farm_inventory\AssetInventoryInterface: '@asset.inventory'
  farm_inventory.log_event_subscriber:
    class: Drupal\farm_inventory\EventSubscriber\LogEventSubscriber
    tags:
      - { name: 'event_subscriber' }

  Drupal\farm_inventory\Hook\FarmInventoryViewsHooks:
    class: Drupal\farm_inventory\Hook\FarmInventoryViewsHooks
    autowire: true

  Drupal\farm_inventory\Hook\FarmInventoryHooks:
    class: Drupal\farm_inventory\Hook\FarmInventoryHooks
    autowire: true
