<?php

/**
 * @file
 * The farmOS UI Theme module.
 */

declare(strict_types=1);

/**
 * Splits content into a stacked two-column layout.
 *
 * @param array $variables
 *   A $variables array that contains a 'content' item, which will be replaced
 *   by a stacked two-column layout.
 * @param string $entity_type
 *   The entity type.
 */
function farm_ui_theme_build_stacked_twocol_layout(array &$variables, string $entity_type) {

  // Ask modules for a list of region items.
  $region_items = \Drupal::moduleHandler()->invokeAll('farm_ui_theme_region_items', [$entity_type]);

  // Split the content items into regions.
  $regions = [];
  foreach ($variables['content'] as $index => $item) {
    $region = 'first';
    foreach ($region_items as $region_name => $items) {
      if (in_array($index, $items)) {
        $region = $region_name;
        break;
      }
    }
    $regions[$region][$index] = $item;
  }

  // Build the layout.
  /** @var \Drupal\Core\Layout\LayoutInterface $layout */
  $layout = \Drupal::service('plugin.manager.core.layout')->createInstance('layout_twocol', []);
  $variables['content'] = $layout->build($regions);
}
