<?php

/**
 * @file
 * The farmOS UI Theme module.
 */

declare(strict_types=1);

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\asset\Entity\AssetInterface;
use Drupal\organization\Entity\OrganizationInterface;
use Drupal\plan\Entity\PlanInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_ui_theme_form_asset_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\asset\Entity\AssetInterface $entity */
  $entity = $form_object->getEntity();
  farm_ui_theme_set_archived_message($entity);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_ui_theme_form_plan_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\asset\Entity\AssetInterface $entity */
  $entity = $form_object->getEntity();
  farm_ui_theme_set_archived_message($entity);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_ui_theme_form_quick_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'farm_ui_theme/quick';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'help_block') {
    $variables['#attached']['library'][] = 'farm_ui_theme/help';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_field(&$variables) {
  if ($variables['field_type'] == 'comment') {
    $variables['attributes']['class'][] = 'gin-layer-wrapper';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_toolbar(&$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/toolbar';
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function farm_ui_theme_block_view_farm_powered_by_block_alter(array &$build, BlockPluginInterface $block) {
  $build['#attached']['library'][] = 'farm_ui_theme/footer';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_field__flag(array &$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/flag';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_field__image(array &$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/image';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_asset__full(&$variables) {
  if (!empty($variables['asset']) && $variables['asset'] instanceof AssetInterface) {
    farm_ui_theme_set_archived_message($variables['asset']);
  }
  farm_ui_theme_build_stacked_twocol_layout($variables, 'asset');
  $variables['#attached']['library'][] = 'farm_ui_theme/layout';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_log__full(&$variables) {
  farm_ui_theme_build_stacked_twocol_layout($variables, 'log');
  $variables['#attached']['library'][] = 'farm_ui_theme/layout';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/regions';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_page__dashboard(&$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/dashboard';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_organization__full(&$variables) {
  if (!empty($variables['organization']) && $variables['organization'] instanceof OrganizationInterface) {
    farm_ui_theme_set_archived_message($variables['organization']);
  }
  farm_ui_theme_build_stacked_twocol_layout($variables, 'organization');
  $variables['#attached']['library'][] = 'farm_ui_theme/layout';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_plan__full(&$variables) {
  if (!empty($variables['plan']) && $variables['plan'] instanceof PlanInterface) {
    farm_ui_theme_set_archived_message($variables['plan']);
  }
  farm_ui_theme_build_stacked_twocol_layout($variables, 'plan');
  $variables['#attached']['library'][] = 'farm_ui_theme/layout';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_ui_theme_preprocess_views_view(&$variables) {
  $variables['#attached']['library'][] = 'farm_ui_theme/views';
}

/**
 * Adds a warning message to entities that are archived.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 *   The entity.
 */
function farm_ui_theme_set_archived_message(FieldableEntityInterface $entity) {
  if ($entity->get('archived')->value) {
    \Drupal::messenger()->addWarning(t('This @entity_type is archived. Archived @entity_types should only be edited if they need corrections.', ['@entity_type' => strtolower($entity->getEntityType()->getLabel()->render()), '@entity_types' => strtolower($entity->getEntityType()->getPluralLabel()->render())]));
  }
}

/**
 * Splits content into a stacked two-column layout.
 *
 * @param array $variables
 *   A $variables array that contains a 'content' item, which will be replaced
 *   by a stacked two-column layout.
 * @param string $entity_type
 *   The entity type.
 */
function farm_ui_theme_build_stacked_twocol_layout(array &$variables, string $entity_type) {

  // Ask modules for a list of region items.
  $region_items = \Drupal::moduleHandler()->invokeAll('farm_ui_theme_region_items', [$entity_type]);

  // Split the content items into regions.
  $regions = [];
  foreach ($variables['content'] as $index => $item) {
    $region = 'first';
    foreach ($region_items as $region_name => $items) {
      if (in_array($index, $items)) {
        $region = $region_name;
        break;
      }
    }
    $regions[$region][$index] = $item;
  }

  // Build the layout.
  /** @var \Drupal\Core\Layout\LayoutInterface $layout */
  $layout = \Drupal::service('plugin.manager.core.layout')->createInstance('layout_twocol', []);
  $variables['content'] = $layout->build($regions);
}
