<?php

/**
 * @file
 * The data stream module.
 */

declare(strict_types=1);

use Drupal\data_stream\Entity\DataStreamInterface;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function data_stream_data_stream_delete(DataStreamInterface $data_stream) {

  // If this is a "basic" data stream, delete data associated with it.
  if ($data_stream->bundle() == 'basic' && !empty($data_stream->id())) {
    \Drupal::database()->delete('data_stream_basic')
      ->condition('id', $data_stream->id())
      ->execute();
  }
}
