<?php

/**
 * @file
 * Contains farm_api.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\entity\BundleFieldDefinition;

/**
 * Implements hook_consumers_list_alter().
 *
 * Display the client_id in the list of consumers.
 */
function farm_api_consumers_list_alter(&$data, $context) {
  if ($context['type'] === 'header') {
    $data['client_id'] = t('Client ID');
  }
  elseif ($context['type'] === 'row') {
    $entity = $context['entity'];

    $data['client_id'] = NULL;
    if ($client_id = $entity->get('client_id')->value) {
      $data['client_id'] = $client_id;
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function farm_api_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add allowed_origins field to the consumer entity.
  if ($entity_type->id() == 'consumer') {
    $fields['allowed_origins'] = BundleFieldDefinition::create('string')
      ->setLabel(t('Allowed origins'))
      ->setDescription(t('Configure CORS origins for this consumer.'))
      ->setCardinality(BaseFieldDefinition::CARDINALITY_UNLIMITED)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'size' => 255,
          'placeholder' => 'https://example.com',
        ],
      ]);
  }

  return $fields;
}

/**
 * Implements hook_farm_api_allow_resource_types().
 */
function farm_api_farm_api_allow_resource_types() {

  // Allow farmOS core entity types on behalf of the modules that provide them.
  return [
    'asset',
    'asset_type',
    'data_stream',
    'data_stream_type',
    'file',
    'log',
    'log_type',
    'plan',
    'plan_type',
    'plan_record',
    'plan_record_type',
    'quantity',
    'quantity_type',
    'taxonomy_term',
    'taxonomy_vocabulary',
    'user',
    'user_role',
  ];
}
