<?php

/**
 * @file
 * Contains farm_transplanting.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_transplanting\Hook\FarmTransplantingHooks;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_form_display_alter().
 */
#[LegacyHook]
function farm_transplanting_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  \Drupal::service(FarmTransplantingHooks::class)->entityFormDisplayAlter($form_display, $context);
}

/**
 * Implements hook_entity_view_display_alter().
 */
#[LegacyHook]
function farm_transplanting_entity_view_display_alter(EntityViewDisplayInterface $display, array $context) {
  \Drupal::service(FarmTransplantingHooks::class)->entityViewDisplayAlter($display, $context);
}
