<?php

/**
 * @file
 * Contains farm_entity_views.module.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 */
function farm_entity_views_module_implements_alter(&$implementations, $hook) {

  // Make sure this module's hook_modules_installed runs after the entity
  // module's implementation, so that we rebuild views data after bundle fields
  // are installed.
  $module = 'farm_entity_views';
  if ($hook == 'modules_installed') {
    $implementation = [$module => $implementations[$module]];
    unset($implementations[$module]);
    $implementations = array_merge($implementations, $implementation);
  }
}
