<?php

/**
 * @file
 * Contains farm_entity_fields.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_entity_fields\Hook\FarmEntityFieldsHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_entity_fields_entity_base_field_info(EntityTypeInterface $entity_type)
{
    return \Drupal::service(FarmEntityFieldsHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
#[LegacyHook]
function farm_entity_fields_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type)
{
    return \Drupal::service(FarmEntityFieldsHooks::class)->entityBaseFieldInfoAlter($fields, $entity_type);
}
