<?php

/**
 * @file
 * Contains farm_entity_test.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_entity_test\Hook\FarmEntityTestHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_entity_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(FarmEntityTestHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
#[LegacyHook]
function farm_entity_test_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle) {
  return \Drupal::service(FarmEntityTestHooks::class)->farmEntityBundleFieldInfo($entity_type, $bundle);
}
