<?php

/**
 * @file
 * Contains farm_api_test_allowed_resources.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_api_test_allowed_resources\Hook\FarmApiTestAllowedResourcesHooks;

/**
 * Implements hook_farm_api_allow_resource_types().
 */
#[LegacyHook]
function farm_api_test_allowed_resources_farm_api_allow_resource_types() {

  return \Drupal::service(FarmApiTestAllowedResourcesHooks::class)->farmApiAllowResourceTypes();
}

/**
 * Implements hook_farm_api_allow_resource_types_alter().
 */
#[LegacyHook]
function farm_api_test_allowed_resources_farm_api_allow_resource_types_alter(&$entity_types) {

  \Drupal::service(FarmApiTestAllowedResourcesHooks::class)->farmApiAllowResourceTypesAlter($entity_types);
}
