<?php

/**
 * @file
 * Contains farm_comment_asset.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_comment_asset\Hook\FarmCommentAssetHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_comment_asset_entity_base_field_info(EntityTypeInterface $entity_type)
{
    return \Drupal::service(FarmCommentAssetHooks::class)->entityBaseFieldInfo($entity_type);
}
