<?php

/**
 * @file
 * Contains farm_entity_contrib_test.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_entity_contrib_test\Hook\FarmEntityContribTestHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
#[LegacyHook]
function farm_entity_contrib_test_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle)
{
    return \Drupal::service(FarmEntityContribTestHooks::class)->farmEntityBundleFieldInfo($entity_type, $bundle);
}
