<?php

/**
 * @file
 * Contains farm_comment_log.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_comment_log\Hook\FarmCommentLogHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_comment_log_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(FarmCommentLogHooks::class)->entityBaseFieldInfo($entity_type);
}
