<?php

/**
 * @file
 * Contains farm_parent.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_parent\Hook\FarmParentHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_parent_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(FarmParentHooks::class)->entityBaseFieldInfo($entity_type);
}
