<?php

/**
 * @file
 * Hooks implemented by the Farm Manager module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_manager\Hook\FarmManagerHooks;

/**
 * Implements hook_oauth2_scope_info_alter().
 */
#[LegacyHook]
function farm_manager_oauth2_scope_info_alter(array &$scopes) {

  \Drupal::service(FarmManagerHooks::class)->oauth2ScopeInfoAlter($scopes);
}
