<?php

/**
 * @file
 * Contains farm_entity.module.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 */
function farm_entity_module_implements_alter(&$implementations, $hook) {

  // Make sure this module's hook_entity_type_build() runs before the
  // entity module's implementation, so that we can override the bundle plugin
  // handler, and so that we can set the Log entity type's bundle_plugin_type.
  $module = 'farm_entity';
  if ($hook == 'entity_type_build') {
    $implementation = [$module => $implementations[$module]];
    unset($implementations[$module]);
    $implementations = array_merge($implementation, $implementations);
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function farm_entity_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */

  // Remove the form for reverting entity revisions.
  // We do this because farmOS modules provide entity constraint validation
  // logic that may depend on other entities in the database (not just the data
  // in the entity being reverted), and Drupal does not validate entities when
  // they are reverted. This could result in entities that no longer validate,
  // leaving the database in a state that would normally be considered invalid.
  foreach ($entity_types as $entity_type) {
    if ($entity_type->hasLinkTemplate('revision-revert-form')) {
      $links = $entity_type->getLinkTemplates();
      unset($links['revision-revert-form']);
      $entity_type->set('links', $links);
    }
  }
}
