<?php

/**
 * @file
 * The farm_ui_dashboard_test module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_ui_dashboard_test\Hook\FarmUiDashboardTestHooks;

/**
 * Implements hook_farm_dashboard_panes().
 */
#[LegacyHook]
function farm_ui_dashboard_test_farm_dashboard_panes() {
  return \Drupal::service(FarmUiDashboardTestHooks::class)->farmDashboardPanes();
}
