<?php

/**
 * @file
 * Contains farm_log_category.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_log_category\Hook\FarmLogCategoryHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function farm_log_category_entity_base_field_info(EntityTypeInterface $entity_type)
{
    return \Drupal::service(FarmLogCategoryHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_farm_ui_theme_region_items().
 */
#[LegacyHook]
function farm_log_category_farm_ui_theme_region_items(string $entity_type) {

  return \Drupal::service(FarmLogCategoryHooks::class)->farmUiThemeRegionItems($entity_type);
}
