<?php

/**
 * @file
 * Contains farm_farm.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_farm_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add a Farm reference field to assets.
  if ($entity_type->id() == 'asset') {
    $options = [
      'type' => 'entity_reference',
      'label' => t('Farm'),
      'description' => t('What farm is this associated with?'),
      'target_type' => 'organization',
      'target_bundle' => 'farm',
      'multiple' => TRUE,
      'weight' => [
        'form' => 55,
        'view' => -5,
      ],
    ];
    $fields['farm'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);

    // Add a constraint to ensure that location assets are in the same farm as
    // their parents and children.
    $fields['farm']->addConstraint('LocationAssetParentFarm');

    // Add a constraint to ensure that the farm does not change if there are
    // any movement logs that reference it (in either asset or location field).
    $fields['farm']->addConstraint('AssetMovementFarm');

    // If the farm_group module is installed, add a constraint to ensure that
    // the farm does not change if there are any group assignment logs that
    // reference it (in either asset or group field).
    if (\Drupal::moduleHandler()->moduleExists('farm_group')) {
      $fields['farm']->addConstraint('AssetGroupAssignmentFarm');
    }
  }

  return $fields;
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function farm_farm_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {

  // Only modify log fields.
  if ($entity_type->id() != 'log') {
    return;
  }

  // If the is_movement field exists, add a constraint to ensure that assets
  // can't be moved between farms.
  if (!empty($fields['is_movement'])) {
    $fields['is_movement']->addConstraint('LogMovementFarm');
  }

  // If the is_group_membership field exists, add a constraint to ensure that
  // assets can't be assigned to groups in a different farm.
  if (!empty($fields['is_group_assignment'])) {
    $fields['is_group_assignment']->addConstraint('LogGroupAssignmentFarm');
  }
}

/**
 * Implements hook_farm_import_csv_base_fields().
 */
function farm_farm_farm_import_csv_base_fields(string $entity_type) {
  $base_fields = [];

  // Add farm organization base field to asset CSV importers.
  if ($entity_type == 'asset') {
    $base_fields[] = 'farm';
  }

  return $base_fields;
}

/**
 * Implements hook_farm_ui_views_base_fields().
 */
function farm_farm_farm_ui_views_base_fields(string $entity_type) {
  $base_fields = [];

  // Add farm organization base field to farmOS asset Views.
  if ($entity_type == 'asset') {
    $base_fields[] = 'farm';
  }

  return $base_fields;
}

/**
 * Implements hook_farm_ui_theme_field_group_items().
 */
function farm_farm_farm_ui_theme_field_group_items(string $entity_type, string $bundle) {
  if ($entity_type == 'asset') {
    return [
      'farm' => 'meta',
    ];
  }
  return [];
}

/**
 * Implements hook_farm_ui_theme_region_items().
 */
function farm_farm_farm_ui_theme_region_items(string $entity_type) {
  if ($entity_type == 'asset') {
    return [
      'second' => [
        'farm',
      ],
    ];
  }
  return [];
}
