<?php

/**
 * @file
 * Contains farm_quick_movement.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_quick_movement\Hook\FarmQuickMovementHooks;

/**
 * Implements hook_entity_base_field_info_alter().
 */
#[LegacyHook]
function farm_quick_movement_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  \Drupal::service(FarmQuickMovementHooks::class)->entityBaseFieldInfoAlter($fields, $entity_type);
}
