<?php

/**
 * @file
 * Hooks and customizations for the asset module.
 */

declare(strict_types=1);

use Drupal\Core\Render\Element;

/**
 * Prepares variables for asset templates.
 *
 * Default template: asset.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the asset information and any
 *     fields attached to the asset. Properties used:
 *     - #asset: A \Drupal\asset\Entity\Asset object. The asset entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_asset(array &$variables) {
  $variables['asset'] = $variables['elements']['#asset'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
