<?php

/**
 * @file
 * Contains farm_settings.module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\farm_settings\Hook\FarmSettingsHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function farm_settings_help($route_name, RouteMatchInterface $route_match)
{
    return \Drupal::service(FarmSettingsHooks::class)->help($route_name, $route_match);
}
