<?php

/**
 * @file
 * The farmOS UI Views module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_ui_views_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Load form state storage and bail if the View is not stored.
  $storage = $form_state->getStorage();
  if (empty($storage['view'])) {
    return;
  }

  /** @var \Drupal\views\ViewExecutable $view */
  $view = $storage['view'];

  // Check if the view display has the collapsible_filter extender enabled.
  $extenders = $view->getDisplay()->getExtenders();
  if (array_key_exists('collapsible_filter', $extenders) && $extenders['collapsible_filter']->options['collapsible']) {

    // Render filters in collapsible details element.
    // Only open the filters if a non-default filter value is provided.
    // This is needed to prevent the filter from opening when click sort is
    // applied and all default filter values are passed as query parameters.
    $open_input = FALSE;
    foreach ($view->getExposedInput() as $filter_name => $filter_value) {
      /**
       * @var string $filter_name
       * @var string|array $filter_value
       */

      // Check if the exposed input is for a filter.
      if (isset($view->filter[$filter_name])) {

        // Get the default filter value.
        $default_filter_value = $view->filter[$filter_name]->value;

        // If the default is an array with one value and a single string value
        // is provided in input, consider the default filter to be a string
        // instead of an array. This fixes the status filter.
        if (is_array($default_filter_value) && count($default_filter_value) == 1 && !is_array($filter_value)) {
          $default_filter_value = reset($default_filter_value);
        }

        // Open the filters if the filter value does not equal the default.
        if ($filter_value != $default_filter_value) {
          $open_input = TRUE;
          break;
        }
      }
    }
    $form['#theme_wrappers']['details'] = [
      '#title' => t('Filter'),
      '#attributes' => [
        // Open if there is exposed input.
        'open' => $open_input,
      ],
      '#summary_attributes' => [],
    ];
    $form['#attached']['library'][] = 'farm_ui_views/views_collapsible_filter';
  }

  // We only want to alter the Views we provide.
  if (!in_array($storage['view']->id(), ['farm_asset', 'farm_log', 'farm_plan'])) {
    return;
  }

  // If there is no exposed filter for flags, bail.
  if (empty($form['flag_value'])) {
    return;
  }

  // Get the entity type and (maybe) bundle.
  $entity_type = $storage['view']->getBaseEntityType()->id();
  $bundle = farm_ui_views_get_bundle_argument($storage['view'], $storage['display']['id'], $storage['view']->args);
  $bundles = !empty($bundle) ? [$bundle] : [];
  $allowed_options = farm_flag_options($entity_type, $bundles, TRUE);
  $form['flag_value']['#options'] = $allowed_options;
}

/**
 * Helper function for getting the bundle from a "By Type" display's arguments.
 *
 * @param \Drupal\views\ViewExecutable $view
 *   The View object.
 * @param string $display_id
 *   The display ID.
 * @param array $args
 *   Arguments for the View.
 *
 * @return string
 *   Returns the bundle, or empty string if no bundle argument is found.
 */
function farm_ui_views_get_bundle_argument(ViewExecutable $view, string $display_id, array $args) {
  $bundle = '';
  if ($view->id() == 'farm_log' && $display_id == 'page_asset' && !empty($args[1]) && $args[1] != 'all') {
    $bundle = $args[1];
  }
  elseif (in_array($view->id(), ['farm_asset', 'farm_log']) && $display_id == 'page_term' && !empty($args[1]) && $args[1] != 'all') {
    $bundle = $args[1];
  }
  elseif (in_array($view->id(), ['farm_organization_asset', 'farm_organization_log']) && $display_id == 'page_type' && isset($args[1]) && $args[1] != 'all') {
    $bundle = $args[1];
  }
  elseif ($display_id == 'page_type' && !empty($args[0])) {
    $bundle = $args[0];
  }
  return $bundle;
}
